version: '3.8'

services:
  my_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8003
    volumes:
      - .:/app
    ports:
      - "8003:8003"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  
      - "5672:5672"  
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  celery:
    build: .
    command: celery -A drf_site worker -l info --pool=solo
    volumes:
      - .:/app
    working_dir: /app/DRF

    depends_on:
      - rabbitmq
      - my_web

volumes:
  postgres_data: