version: '3.8'

services:
  my_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - sqlite_data:/app/db.sqlite3
    ports:
      - "8000:8000"

volumes:
  sqlite_data: