# Generated by Django 5.0.7 on 2024-08-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_follow_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user',
        ),
    ]
